###########################################################################################
#
#  DEV ENVIRONMENT VARIABLES
#
###########################################################################################

# Just an example use case
# enable_analytics: no
_site_root: /versus/statamic/
_site_url: ~philippe/versus/statamic/