###########################################################################################
#
#  DEV ENVIRONMENT VARIABLES
#
###########################################################################################

# Just an example use case
# enable_analytics: no
_site_root: /
_site_url: /